"""empty message

Revision ID: 0a2a57eea916
Revises: 5f46d72de9cd
Create Date: 2019-09-18 11:25:27.635702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2a57eea916'
down_revision = '5f46d72de9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('product', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('product', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('product', sa.Column('object_', sa.String(), nullable=True))
    op.add_column('product', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'url')
    op.drop_column('product', 'object_')
    op.drop_column('product', 'description')
    op.drop_column('product', 'created')
    op.drop_column('product', 'active')
    # ### end Alembic commands ###
