"""empty message

Revision ID: 157fb06ba3f0
Revises: c76fa9762925
Create Date: 2019-09-18 17:31:13.760828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157fb06ba3f0'
down_revision = 'c76fa9762925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('coupon', 'id_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('id_', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('coupon', 'id')
    # ### end Alembic commands ###
