"""empty message

Revision ID: 1bde30247c69
Revises: 05c0cfa2611c
Create Date: 2019-09-10 12:59:16.340337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bde30247c69'
down_revision = '05c0cfa2611c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('value', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'value')
    # ### end Alembic commands ###
