"""empty message

Revision ID: 553fcb9041bd
Revises: 0a2a57eea916
Create Date: 2019-09-18 11:59:32.233713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '553fcb9041bd'
down_revision = '0a2a57eea916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('product', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('product', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('product', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('product', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
