"""empty message

Revision ID: 5c205fb5d22e
Revises: f7b53246d1e0
Create Date: 2019-09-18 17:50:29.792016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c205fb5d22e'
down_revision = 'f7b53246d1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('coupon', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('coupon', 'id_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('id_', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('coupon', 'name')
    op.drop_column('coupon', 'id')
    # ### end Alembic commands ###
