"""empty message

Revision ID: 5f46d72de9cd
Revises: bf97ef746ae6
Create Date: 2019-09-13 10:32:39.887792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f46d72de9cd'
down_revision = 'bf97ef746ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'prod_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('prod_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
