"""empty message

Revision ID: 782da3c8bbcb
Revises: ad4e38eded33
Create Date: 2019-09-18 18:04:51.542644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782da3c8bbcb'
down_revision = 'ad4e38eded33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'created')
    # ### end Alembic commands ###
