"""empty message

Revision ID: 966464cd13a1
Revises: a4916e1d6fc8
Create Date: 2019-09-18 17:20:03.872179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966464cd13a1'
down_revision = 'a4916e1d6fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('coupon', 'id_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('id_', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('coupon', 'id')
    # ### end Alembic commands ###
