"""changed coupon model

Revision ID: 996ca686aa0d
Revises: 491bcaef1db9
Create Date: 2019-09-18 16:42:31.471715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996ca686aa0d'
down_revision = '491bcaef1db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('duration', sa.String(), nullable=False))
    op.add_column('coupon', sa.Column('id_', sa.String(), nullable=False))
    op.add_column('coupon', sa.Column('name', sa.String(), nullable=True))
    op.add_column('coupon', sa.Column('object_', sa.String(), nullable=True))
    op.add_column('coupon', sa.Column('percent_off', sa.Float(), nullable=False))
    op.drop_constraint('coupon_uuid_key', 'coupon', type_='unique')
    op.drop_column('coupon', 'id')
    op.drop_column('coupon', 'code')
    op.drop_column('coupon', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('uuid', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('coupon', sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('coupon', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('coupon_uuid_key', 'coupon', ['uuid'])
    op.drop_column('coupon', 'percent_off')
    op.drop_column('coupon', 'object_')
    op.drop_column('coupon', 'name')
    op.drop_column('coupon', 'id_')
    op.drop_column('coupon', 'duration')
    # ### end Alembic commands ###
