"""empty message

Revision ID: ad4e38eded33
Revises: 5c205fb5d22e
Create Date: 2019-09-18 17:52:25.320824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4e38eded33'
down_revision = '5c205fb5d22e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('id_', sa.String(), nullable=False))
    op.drop_column('coupon', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('coupon', 'id_')
    # ### end Alembic commands ###
