"""empty message

Revision ID: afdd396143f5
Revises: dc0df2590a28
Create Date: 2019-09-11 22:55:46.784904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'afdd396143f5'
down_revision = 'dc0df2590a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupon', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupon', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
