"""empty message

Revision ID: bf97ef746ae6
Revises: 2a9a27f0584d
Create Date: 2019-09-12 15:09:56.695948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf97ef746ae6'
down_revision = '2a9a27f0584d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'sku')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
