"""empty message

Revision ID: c76fa9762925
Revises: 966464cd13a1
Create Date: 2019-09-18 17:29:21.528650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76fa9762925'
down_revision = '966464cd13a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('id_', sa.String(), nullable=False))
    op.drop_column('coupon', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('coupon', 'id_')
    # ### end Alembic commands ###
