"""added name column back to coupon model

Revision ID: f350010ad521
Revises: 20ac59e94098
Create Date: 2019-09-18 16:56:32.956358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f350010ad521'
down_revision = '20ac59e94098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'name')
    # ### end Alembic commands ###
