"""empty message

Revision ID: f7b53246d1e0
Revises: 157fb06ba3f0
Create Date: 2019-09-18 17:45:49.156352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b53246d1e0'
down_revision = '157fb06ba3f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('id_', sa.String(), nullable=False))
    op.drop_column('coupon', 'name')
    op.drop_column('coupon', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('coupon', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('coupon', 'id_')
    # ### end Alembic commands ###
